// Static resource data — Northern Virginia organizations
const RESOURCES = [
  {
    id: "food-for-others",
    name: "Food for Others",
    category: "Food",
    description: "Regional food bank serving 1,800+ families weekly with emergency food distribution across NoVA.",
    address: "2938 Prosperity Ave, Fairfax, VA 22031",
    lat: 38.8566,
    lng: -77.2607,
    website: "https://foodforothers.org",
    approved: true,
    featured: true,
  },
  {
    id: "capital-area-food-bank-lorton",
    name: "Capital Area Food Bank (Lorton)",
    category: "Food",
    description: "Northern Virginia hub of the region's largest food bank, distributing millions of meals yearly.",
    address: "6833 Hill Park Dr, Lorton, VA 22079",
    lat: 38.7006,
    lng: -77.2197,
    website: "https://capitalareafoodbank.org",
    approved: true,
    featured: true,
  },
  {
    id: "nvfs",
    name: "Northern Virginia Family Service",
    category: "Crisis",
    description: "Provides food, housing, childcare, and wraparound services to 40,000+ individuals annually.",
    address: "10455 White Granite Dr, Suite 100, Oakton, VA 22124",
    lat: 38.8801,
    lng: -77.3216,
    website: "https://nvfs.org",
    approved: true,
    featured: true,
  },
  {
    id: "cornerstones",
    name: "Cornerstones",
    category: "Housing",
    description: "Offers emergency shelter, food pantry, affordable housing, and childcare in the Reston/Herndon corridor.",
    address: "11150 Sunset Hills Rd, Suite 210, Reston, VA 20190",
    lat: 38.9586,
    lng: -77.3570,
    website: "https://cornerstonesva.org",
    approved: true,
    featured: false,
  },
  {
    id: "united-community",
    name: "United Community",
    category: "Crisis",
    description: "Provides food, housing, workforce development, and family services along the Route 1 corridor.",
    address: "7511 Fordson Rd, Alexandria, VA 22306",
    lat: 38.7573,
    lng: -77.0820,
    website: "https://unitedcommunity.org",
    approved: true,
    featured: false,
  },
  {
    id: "homestretch",
    name: "Homestretch",
    category: "Housing",
    description: "Largest transitional housing provider in Fairfax County, helping homeless families achieve permanent housing.",
    address: "303 S Maple Ave, Suite 400, Falls Church, VA 22046",
    lat: 38.8820,
    lng: -77.1711,
    website: "https://homestretchva.org",
    approved: true,
    featured: false,
  },
  {
    id: "facets",
    name: "FACETS",
    category: "Crisis",
    description: "Fights poverty and homelessness in Fairfax through meals, shelter, and supportive family services.",
    address: "10640 Page Ave, Suite 300, Fairfax, VA 22030",
    lat: 38.8462,
    lng: -77.2994,
    website: "https://facetscares.org",
    approved: true,
    featured: false,
  },
  {
    id: "new-hope-housing",
    name: "New Hope Housing",
    category: "Housing",
    description: "Operates 6 shelters and 9 housing programs across Fairfax, Arlington, Alexandria, and Falls Church.",
    address: "8407 Richmond Hwy, Alexandria, VA 22309",
    lat: 38.7219,
    lng: -77.0862,
    website: "https://newhopehousing.org",
    approved: true,
    featured: false,
  },
  {
    id: "habitat-nova",
    name: "Habitat for Humanity of NoVA",
    category: "Housing",
    description: "Builds and repairs affordable homes for lower-income families across Alexandria, Arlington, and Fairfax.",
    address: "3576 Chain Bridge Rd, Fairfax, VA 22030",
    lat: 38.8567,
    lng: -77.3017,
    website: "https://habitatnova.org",
    approved: true,
    featured: false,
  },
  {
    id: "good-shepherd-housing",
    name: "Good Shepherd Housing",
    category: "Housing",
    description: "Reduces homelessness and promotes self-sufficiency through housing and support services in Fairfax.",
    address: "8305 Richmond Hwy, Alexandria, VA 22309",
    lat: 38.7226,
    lng: -77.0869,
    website: "https://goodhousing.org",
    approved: true,
    featured: false,
  },
  {
    id: "arlington-thrive",
    name: "Arlington Thrive",
    category: "Crisis",
    description: "Provides rapid financial assistance for rent, utilities, and medical care to prevent Arlington residents from falling into crisis.",
    address: "2929 Columbia Pike, Arlington, VA 22204",
    lat: 38.8537,
    lng: -77.0974,
    website: "https://arlingtonthrive.org",
    approved: true,
    featured: false,
  },
  {
    id: "acts-prince-william",
    name: "ACTS of Prince William",
    category: "Crisis",
    description: "Offers emergency food, shelter, and utility assistance to families in Prince William County.",
    address: "14473 Minnieville Rd, Dale City, VA 22193",
    lat: 38.6343,
    lng: -77.3394,
    website: "https://actspwc.org",
    approved: true,
    featured: false,
  },
  {
    id: "shelter-house",
    name: "Shelter House",
    category: "Housing",
    description: "Operates family shelters and Fairfax County's only 24/7 domestic violence shelter.",
    address: "3120 Fairview Park Dr, Falls Church, VA 22042",
    lat: 38.8706,
    lng: -77.2354,
    website: "https://shelterhouse.org",
    approved: true,
    featured: false,
  },
  {
    id: "herndon-reston-fish",
    name: "Herndon-Reston FISH",
    category: "Food",
    description: "Provides emergency food, financial aid, and basic necessities to residents of Herndon and Reston since 1969.",
    address: "336 Victory Dr, Herndon, VA 20170",
    lat: 38.9696,
    lng: -77.3861,
    website: "https://herndonrestonfish.org",
    approved: true,
    featured: false,
  },
  {
    id: "echo",
    name: "ECHO (Ecumenical Community Helping Others)",
    category: "Food",
    description: "Offers food, financial assistance, and clothing to low-income families in Springfield and Burke areas.",
    address: "7205 Old Keene Mill Rd, Springfield, VA 22150",
    lat: 38.7787,
    lng: -77.1984,
    website: "https://echo-inc.org",
    approved: true,
    featured: false,
  },
  {
    id: "casa-virginia",
    name: "CASA de Virginia",
    category: "Legal",
    description: "Advocates for and empowers Latino immigrants through legal services, education, and workforce development.",
    address: "8119 Holland Rd, Alexandria, VA 22306",
    lat: 38.7541,
    lng: -77.0929,
    website: "https://wearecasa.org",
    approved: true,
    featured: false,
  },
  {
    id: "lajc",
    name: "Legal Aid Justice Center",
    category: "Legal",
    description: "Provides free civil legal aid to low-income Virginians facing housing, immigration, and economic justice issues.",
    address: "6066 Leesburg Pike, Suite 520, Falls Church, VA 22041",
    lat: 38.8526,
    lng: -77.1414,
    website: "https://lajc.org",
    approved: true,
    featured: false,
  },
  {
    id: "edu-futuro",
    name: "Edu-Futuro",
    category: "Education",
    description: "Empowers Latino immigrant youth and families through education, mentorship, and leadership programs.",
    address: "3033 Wilson Blvd, Suite 700, Arlington, VA 22201",
    lat: 38.8865,
    lng: -77.0937,
    website: "https://edu-futuro.org",
    approved: true,
    featured: false,
  },
  {
    id: "computer-core",
    name: "Computer CORE",
    category: "Education",
    description: "Provides free digital skills and career training to underserved adults across Northern Virginia.",
    address: "2941 Fairview Park Dr, Suite 500, Falls Church, VA 22042",
    lat: 38.8701,
    lng: -77.2349,
    website: "https://computercore.org",
    approved: true,
    featured: false,
  },
  {
    id: "english-empowerment-center",
    name: "English Empowerment Center",
    category: "Education",
    description: "Offers free English literacy and citizenship classes to adult immigrants in Northern Virginia.",
    address: "2210 Mt Vernon Ave, Alexandria, VA 22301",
    lat: 38.8354,
    lng: -77.0660,
    website: "https://englishempowermentcenter.org",
    approved: true,
    featured: false,
  },
  {
    id: "doorways",
    name: "Doorways for Women and Families",
    category: "Housing",
    description: "Provides shelter, housing, and support services for survivors of domestic violence and those facing homelessness.",
    address: "6800 N Quincy St, Arlington, VA 22213",
    lat: 38.9086,
    lng: -77.1199,
    website: "https://doorwaysva.org",
    approved: true,
    featured: false,
  },
  {
    id: "loudoun-hunger-relief",
    name: "Loudoun Hunger Relief",
    category: "Food",
    description: "Distributes food to food-insecure individuals and families across Loudoun County.",
    address: "40958 Robin Court, Leesburg, VA 20175",
    lat: 39.1098,
    lng: -77.5573,
    website: "https://loudounhungerrelief.org",
    approved: true,
    featured: false,
  },
  {
    id: "mobile-hope-loudoun",
    name: "Mobile Hope Loudoun",
    category: "Crisis",
    description: "Meets young people experiencing homelessness in Loudoun County where they are with food, supplies, and support.",
    address: "42395 Ryan Rd, Suite 112, Brambleton, VA 20148",
    lat: 38.9964,
    lng: -77.5337,
    website: "https://mobile-hope.org",
    approved: true,
    featured: false,
  },
  {
    id: "oar-fairfax",
    name: "OAR of Fairfax County",
    category: "Crisis",
    description: "Helps individuals reintegrate after incarceration through housing, employment, and community support.",
    address: "10640 Page Ave, Suite 200, Fairfax, VA 22030",
    lat: 38.8462,
    lng: -77.2994,
    website: "https://oarfairfax.org",
    approved: true,
    featured: false,
  },
  {
    id: "second-story",
    name: "Second Story",
    category: "Housing",
    description: "Provides crisis shelter, housing, and support services for homeless and at-risk youth ages 13–24.",
    address: "2100 Gallows Rd, Vienna, VA 22182",
    lat: 38.9002,
    lng: -77.2284,
    website: "https://second-story.org",
    approved: true,
    featured: false,
  },
  {
    id: "rebuilding-together-nova",
    name: "Rebuilding Together Arlington/Fairfax",
    category: "Housing",
    description: "Provides free critical home repairs for low-income homeowners and seniors across NoVA.",
    address: "10723 Main St, Suite 135, Fairfax, VA 22030",
    lat: 38.8477,
    lng: -77.3078,
    website: "https://rebuildingtogetherva.org",
    approved: true,
    featured: false,
  },
  {
    id: "hopkins-house",
    name: "Hopkins House",
    category: "Education",
    description: "Offers affordable early childhood education and family support services in Arlington since 1939.",
    address: "1224 N Fillmore St, Arlington, VA 22201",
    lat: 38.8873,
    lng: -77.0928,
    website: "https://hopkinshouse.org",
    approved: true,
    featured: false,
  },
  {
    id: "ecdc",
    name: "Ethiopian Community Development Council",
    category: "Crisis",
    description: "Provides refugee resettlement, workforce development, and community services to immigrant populations.",
    address: "901 S Highland St, Arlington, VA 22204",
    lat: 38.8607,
    lng: -77.1003,
    website: "https://ecdcus.org",
    approved: true,
    featured: false,
  },
  {
    id: "dulles-south-food-pantry",
    name: "Dulles South Food Pantry",
    category: "Food",
    description: "Serves food-insecure families in the rapidly growing Dulles South/Loudoun County corridor.",
    address: "24997 Riding Plaza, Suite 130, South Riding, VA 20152",
    lat: 38.9434,
    lng: -77.5098,
    website: "https://dullessouthfoodpantry.org",
    approved: true,
    featured: false,
  },
  {
    id: "britepaths",
    name: "Britepaths",
    category: "Crisis",
    description: "Connects Fairfax County residents to financial coaching, tutoring, holiday assistance, and basic needs support.",
    address: "3959 Pender Dr, Suite 200, Fairfax, VA 22030",
    lat: 38.8611,
    lng: -77.3089,
    website: "https://britepaths.org",
    approved: true,
    featured: false,
  },
];

async function fetchApprovedResources() {
  return RESOURCES.filter((r) => r.approved);
}

async function fetchFeaturedResources(limit = 3) {
  return RESOURCES.filter((r) => r.approved && r.featured).slice(0, limit);
}

async function submitResource(resource) {
  // For now, just log to console since we're using static data
  console.log("Resource submission (would be sent to backend):", resource);
  return { ...resource, id: Date.now().toString(), approved: false };
}
